# Generated by Django 4.1.7 on 2023-07-18 06:27

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('method', models.CharField(max_length=1000)),
                ('headers', models.CharField(max_length=1000)),
                ('payload', models.CharField(max_length=1000)),
                ('staging_version', models.CharField(max_length=1000)),
                ('EnvironmentName', models.CharField(max_length=1000)),
                ('Testcase_Version', models.CharField(max_length=1000)),
                ('Project_Name', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'Inputdata_IvinPro',
            },
        ),
        migrations.CreateModel(
            name='lifeeazyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('headers', models.CharField(max_length=100)),
                ('payload', models.CharField(max_length=100)),
                ('staging_version', models.CharField(max_length=100)),
                ('EnvironmentName', models.CharField(max_length=100)),
                ('Testcase_Version', models.CharField(max_length=100)),
                ('Project_Name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Inputdata_Lifeeazy',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
